// import "./globals.css";
// import { useLocale } from "next-intl";
// import { notFound } from "next/navigation";
// import { NextIntlClientProvider } from "next-intl";

// export default async function LocaleLayout({ children }) {
//   const locale = useLocale();

//   let messages;
//   try {
//     messages = (await import(`../../messages/${locale}.json`)).default;
//   } catch (error) {
//     notFound();
//   }

//   return (
//     <html lang={locale}>
//       <body className={`${locale == "ar" ? "rtl" : ""}`}>
//         <NextIntlClientProvider locale={locale} messages={messages}>
//           <Navbar />
//           {children}
//           <Footer />
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}